name: Code Quality and Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sast-lint-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21 

    - name: Install Semgrep
      run: |
        pip install semgrep
        semgrep --version

    - name: Run Static Application Security Testing (SAST)
      run: |
        semgrep scan --config=auto .

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
    
    - name: Run Linter
      run: |
        $(go env GOPATH)/bin/golangci-lint run -v --config .golangci.yml ./...

    - name: Build Go Application
      run: |
        go build -o app .
